version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: research-agent-backend
    ports:
      - "8000:8000"
    environment:
      - DEMO_MODE=${DEMO_MODE:-true}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - research-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: research-agent-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - research-network

networks:
  research-network:
    driver: bridge

volumes:
  backend_data: 