services:
  - type: web
    name: research-agent-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn api:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: DEMO_MODE
        value: "true"
      - key: OPENAI_API_KEY
        sync: false
        
  - type: web
    name: research-agent-frontend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run preview
    plan: free
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: research-agent-backend
          property: host 