services:
  - type: web
    name: research-agent-backend  # Make sure this matches your actual backend service name on Render.com
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn api:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: DEMO_MODE
        value: "true"
      - key: OPENAI_API_KEY
        sync: false
        
  - type: web
    name: research-agent-frontend
    env: node
    buildCommand: npm ci && npm run build:render
    startCommand: npm run preview:render -- --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://research-agent-backend.onrender.com 